// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $blog from "./routes/blog.tsx";
import * as $index from "./routes/index.tsx";
import * as $publications from "./routes/publications.tsx";
import * as $software from "./routes/software.tsx";
import * as $BackToTop from "./islands/BackToTop.tsx";
import * as $MobileNav from "./islands/MobileNav.tsx";
import * as $PublicationCard from "./islands/PublicationCard.tsx";
import * as $ThemeProvider from "./islands/ThemeProvider.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/blog.tsx": $blog,
    "./routes/index.tsx": $index,
    "./routes/publications.tsx": $publications,
    "./routes/software.tsx": $software,
  },
  islands: {
    "./islands/BackToTop.tsx": $BackToTop,
    "./islands/MobileNav.tsx": $MobileNav,
    "./islands/PublicationCard.tsx": $PublicationCard,
    "./islands/ThemeProvider.tsx": $ThemeProvider,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
