name: Deploy Website

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}  # Personal Access Token with repo scope

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-basic
            etoolbox
            ifthen
            ifxetex
            ifluatex
            url
            graphicx
            fancyhdr
            tweaklist
            calc
            xsparse
            microtype
            expl3
            tikz
            changepage
            fontawesome5
            academicons
            marvosym
            multirow
            arydshln
            tgpagella
            lmodern
            xcolor
            ebgaramond
            hyperref
            pgf
            tools

      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      # - name: Run tests
      #   run: deno test -A

      - name: Build website
        run: deno task build
