name: Deploy Website

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-basic
            moderncv
            multirow
            arydshln
            fontawesome5
            multibib
            microtype
            geometry
            hyperref
            xcolor
            pgf
            tools
            graphics
            fancyhdr

      - name: Build website
        run: deno task build

      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: _fresh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}