name: Deploy Website

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container:
      image: thomasweise/docker-texlive-full:latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}  # Personal Access Token with repo scope

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      # - name: Run tests
      #   run: deno test -A

      - name: Build website
        run: deno task build
