name: Deploy Website

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Download CV
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow: make.yml
          repo: JordiManyer/curriculum
          path: static

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      # - nameVerify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      # - name: Run tests
      #   run: deno test -A

      - name: Build website
        run: deno task build
